apiVersion: v1
kind: Service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: {{ .Values.ethereum.args.rpcport }}
    targetPort: {{ .Values.ethereum.args.rpcport }}
  selector:
    component: ethereum
metadata:
  name: ethereum-v{{ .Release.Revision }}-service-rpc
