apiVersion: v1
kind: Service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: {{ .Values.ethereum.args.port }}
    targetPort: {{ .Values.ethereum.args.port }}
    name: ethereum-peer
  selector:
    component: ethereum
metadata:
  name: ethereum-service-peer-tcp
