apiVersion: v1
kind: Service
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: {{ .Values.ethereum.args.rpcport }}
    targetPort: {{ .Values.ethereum.args.rpcport }}
    name: ethereum-rpc
  selector:
    component: ethereum
metadata:
  name: ethereum-service-rpc
