apiVersion: v1
kind: Secret
data:
  STELLAR_CORE_DATABASE_URL: {{ .Values.core.secret.STELLAR_CORE_DATABASE_URL | b64enc }}
type: Opaque
metadata:
  name: core-v{{ .Release.Revision }}-{{ .Release.Name }}-secret
