apiVersion: v1
kind: Service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: {{ .Values.core.environment.PEER_PORT }}
    targetPort: {{ .Values.core.environment.PEER_PORT }}
  selector:
    component: core
metadata:
  name: core-v{{ .Release.Revision }}-service-peer
