apiVersion: v1
kind: Service
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: {{ .Values.core.environment.HTTP_PORT }}
    targetPort: {{ .Values.core.environment.HTTP_PORT }}
  selector:
    component: core
metadata:
  name: core-v{{ .Release.Revision }}-service-http
