apiVersion: v1
kind: Secret
data:
  BITCOIND_RPCAUTH: {{ .Values.bitcoin.secret.BITCOIND_RPCAUTH | b64enc }}
type: Opaque
metadata:
  name: bitcoin-v{{ .Release.Revision }}-{{ .Release.Name }}-secret
