apiVersion: v1
kind: Service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: {{ .Values.bitcoin.environment.BITCOIND_PORT }}
    targetPort: {{ .Values.bitcoin.environment.BITCOIND_PORT }}
    name: bitcoin-peer
  selector:
    component: bitcoin
metadata:
  name: bitcoin-service-peer
