apiVersion: v1
kind: Service
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: {{ .Values.bitcoin.environment.BITCOIND_RPCPORT }}
    targetPort: {{ .Values.bitcoin.environment.BITCOIND_RPCPORT }}
    name: bitcoin-rpc
  selector:
    component: bitcoin
metadata:
  name: bitcoin-service-rpc
