apiVersion: v1
kind: Secret
data:
  BIFROST_BITCOIN_RPC_PASS: {{ .Values.bifrost.secret.BIFROST_BITCOIN_RPC_PASS | b64enc }}
  BIFROST_STELLAR_SIGNER_SECRET_KEY: {{ .Values.bifrost.secret.BIFROST_STELLAR_SIGNER_SECRET_KEY | b64enc }}
  DATABASE_URL: {{ .Values.bifrost.secret.DATABASE_URL | b64enc }}
type: Opaque
metadata:
  name: bifrost-v{{ .Release.Revision }}-{{ .Release.Name }}-secret
