apiVersion: v1
kind: Service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: {{ .Values.bifrost.environment.BIFROST_PORT }}
    targetPort: {{ .Values.bifrost.environment.BIFROST_PORT }}
    name: bifrost-http
  selector:
    component: bifrost
metadata:
  name: bifrost-service-http
