apiVersion: v1
kind: Service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: {{ .Values.bifrost.environment.BIFROST_PORT }}
    targetPort: {{ .Values.bifrost.environment.BIFROST_PORT }}
  selector:
    component: bifrost
metadata:
  name: bifrost-v{{ .Release.Revision }}-service-peer
