apiVersion: v1
kind: Secret
data:
  DATABASE_URL: {{ .Values.horizon.secret.DATABASE_URL | b64enc }}
  STELLAR_CORE_DATABASE_URL: {{ .Values.horizon.secret.STELLAR_CORE_DATABASE_URL | b64enc }}
type: Opaque
metadata:
  name: horizon-v{{ .Release.Revision }}-{{ .Release.Name }}-secret
