apiVersion: v1
kind: Service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: {{ .Values.horizon.environment.HTTP_PORT }}
    targetPort: {{ .Values.horizon.environment.HTTP_PORT }}
  selector:
    component: horizon
metadata:
  name: horizon-v{{ .Release.Revision }}-service-http
