apiVersion: v1
kind: Service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: {{ .Values.horizon.environment.PORT }}
    targetPort: {{ .Values.horizon.environment.PORT }}
    name: horizon-http
  selector:
    component: horizon
metadata:
  name: horizon-service-http
